# Generated by Django 5.2.5 on 2025-08-24 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='reposted_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts', to='tweet.tweet'),
        ),
    ]
